### ISSUE TITLE
Implement support for HTTPS

### ISSUE THREAD

**Issue by opensaucerer** [opensaucerer/barf#4]
BARF currently only `Beck()` to an `http` call. We need to make it possible to specify `https` in the `barf.Augument` config thereby allowing certificates and key pairs be passed as necessary either self-signed or not and configuring the server to expose an `https` instance of itself.

**Comment by oxiginedev** [comment]
This looks like something i could do. Do you me giving it a try

**Comment by opensaucerer** [comment]
Hi @Adedaramola for sure, I don't mind you giving it a shot. 
I just added you as the assignee. 
Do review the contribution guide and open a PR once done. Thank you, my chief.

**Comment by oxiginedev** [comment]
sure boss
