### ISSUE TITLE
Changing the name to "Barf is A Remarkable Framework"

### ISSUE THREAD

**Issue by ejemba** [opensaucerer/barf#8]
Hi my friend,

You miss the opportunity to use the tradition of [Recursive Acronym](https://en.wikipedia.org/wiki/Recursive_acronym) !

Can you please change your name !

**Comment by opensaucerer** [comment]
Hi. Thank you for the suggestion. However, this naming brings in an auxiliary verb `is` and also takes out the idea of reference to the Marvel's BARF technology. 

I'm very sorry but we won't be able to change the name 🙏
